// <auto-generated />
using System;
using InventarioEquipos.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarioEquipos.Persistence.Migrations
{
    [DbContext(typeof(InventarioEquiposDbContext))]
    [Migration("20260824180125_InicialNucleoMultiempresa")]
    partial class InicialNucleoMultiempresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_interno");

                    b.Property<decimal>("CostoAdquisicion")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("costo_adquisicion");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_compra");

                    b.Property<DateTime?>("FechaVencimientoGarantia")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_vencimiento_garantia");

                    b.Property<int?>("IdArea")
                        .HasColumnType("int")
                        .HasColumnName("id_area");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int?>("IdResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Moneda")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("numero_serie");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("IdSede");

                    b.HasIndex("IdUbicacion");

                    b.HasIndex("IdEmpresa", "CodigoInterno")
                        .IsUnique()
                        .HasDatabaseName("UQ_Activo_CodigoInterno");

                    b.ToTable("Activo", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_area");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("EntregadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("entregado_por");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_devolucion");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    b.Property<int>("IdUbicacionUso")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion_uso");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("observaciones");

                    b.Property<string>("RecibidoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("recibido_por");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Asignacion_Activo_Activa")
                        .HasFilter("[activa] = 1");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("IdUbicacionUso");

                    b.ToTable("Asignacion", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Baja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_baja");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("autorizado_por");

                    b.Property<string>("DocumentoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("documento_referencia");

                    b.Property<DateTime>("FechaBaja")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_baja");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    b.Property<int>("IdMotivoBaja")
                        .HasColumnType("int")
                        .HasColumnName("id_motivo_baja");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdMotivoBaja");

                    b.ToTable("Baja", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.CategoriaActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Categoria_Activo", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.DetalleInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Encontrado")
                        .HasColumnType("bit")
                        .HasColumnName("encontrado");

                    b.Property<string>("EstadoFisicoObservado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("estado_fisico_observado");

                    b.Property<DateTime>("FechaVerificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_verificacion");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    b.Property<int>("IdInventario")
                        .HasColumnType("int")
                        .HasColumnName("id_inventario");

                    b.Property<int?>("IdUbicacionEncontrada")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion_encontrada");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdInventario");

                    b.HasIndex("IdUbicacionEncontrada");

                    b.ToTable("Detalle_Inventario", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NitCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nit_codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("NitCodigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Empresa_Nit");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.EstadoActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Estado_Activo", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.HistorialCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entidad_afectada");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdRegistroAfectado")
                        .HasColumnType("int")
                        .HasColumnName("id_registro_afectado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("InformacionAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("informacion_anterior");

                    b.Property<string>("InformacionNueva")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("informacion_nueva");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Historial_Cambios", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.InventarioFisico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_inventario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    b.Property<int>("IdUsuarioResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_responsable");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdSede");

                    b.HasIndex("IdUbicacion");

                    b.HasIndex("IdUsuarioResponsable");

                    b.ToTable("Inventario_Fisico", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mantenimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("costo");

                    b.Property<string>("DescripcionProblema")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion_problema");

                    b.Property<string>("EstadoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_mantenimiento");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_programada");

                    b.Property<DateTime?>("FechaRealizado")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_realizado");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdTipoMantenimiento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_mantenimiento");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("responsable");

                    b.Property<string>("TrabajoRealizado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("trabajo_realizado");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdTipoMantenimiento");

                    b.ToTable("Mantenimiento", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.MotivoBaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_motivo_baja");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Motivo_Baja", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("codigo_iso2");

                    b.Property<string>("CodigoIso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("codigo_iso3");

                    b.Property<string>("CodigoTelefonico")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("codigo_telefonico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("MonedaLocal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("moneda_local");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIso2")
                        .IsUnique();

                    b.HasIndex("CodigoIso3")
                        .IsUnique();

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Responsable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdArea")
                        .HasColumnType("int")
                        .HasColumnName("id_area");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Responsable", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdPais");

                    b.ToTable("Sede", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_mantenimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Tipo_Mantenimiento", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Traslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_traslado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaTraslado")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_traslado");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    b.Property<int>("IdUbicacionDestino")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion_destino");

                    b.Property<int>("IdUbicacionOrigen")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion_origen");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("motivo");

                    b.Property<string>("ResponsableTraslado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("responsable_traslado");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdUbicacionDestino");

                    b.HasIndex("IdUbicacionOrigen");

                    b.ToTable("Traslado", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdSede");

                    b.ToTable("Ubicacion", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usuario_login");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_Correo");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_Login");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_empresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EmpresaPredeterminada")
                        .HasColumnType("bit")
                        .HasColumnName("empresa_predeterminada");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdUsuario", "IdEmpresa")
                        .IsUnique()
                        .HasDatabaseName("UQ_UsuarioEmpresa");

                    b.ToTable("Usuario_Empresa", (string)null);
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Activo", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Activo_Area");

                    b.HasOne("InventarioEquipos.Domain.Entities.CategoriaActivo", "CategoriaActivo")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Activo_Categoria");

                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Activo_Empresa");

                    b.HasOne("InventarioEquipos.Domain.Entities.EstadoActivo", "EstadoActivo")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Activo_Estado");

                    b.HasOne("InventarioEquipos.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Activo_Proveedor");

                    b.HasOne("InventarioEquipos.Domain.Entities.Responsable", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Activo_Responsable");

                    b.HasOne("InventarioEquipos.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Activo_Sede");

                    b.HasOne("InventarioEquipos.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Activo_Ubicacion");

                    b.Navigation("Area");

                    b.Navigation("CategoriaActivo");

                    b.Navigation("Empresa");

                    b.Navigation("EstadoActivo");

                    b.Navigation("Proveedor");

                    b.Navigation("Responsable");

                    b.Navigation("Sede");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Area", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Area_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_Activo");

                    b.HasOne("InventarioEquipos.Domain.Entities.Responsable", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_Responsable");

                    b.HasOne("InventarioEquipos.Domain.Entities.Ubicacion", "UbicacionUso")
                        .WithMany()
                        .HasForeignKey("IdUbicacionUso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_Ubicacion");

                    b.Navigation("Activo");

                    b.Navigation("Responsable");

                    b.Navigation("UbicacionUso");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Baja", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Baja_Activo");

                    b.HasOne("InventarioEquipos.Domain.Entities.MotivoBaja", "MotivoBaja")
                        .WithMany()
                        .HasForeignKey("IdMotivoBaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Baja_MotivoBaja");

                    b.Navigation("Activo");

                    b.Navigation("MotivoBaja");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.CategoriaActivo", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Categoria_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.DetalleInventario", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleInventario_Activo");

                    b.HasOne("InventarioEquipos.Domain.Entities.InventarioFisico", "InventarioFisico")
                        .WithMany()
                        .HasForeignKey("IdInventario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleInventario_Inventario");

                    b.HasOne("InventarioEquipos.Domain.Entities.Ubicacion", "UbicacionEncontrada")
                        .WithMany()
                        .HasForeignKey("IdUbicacionEncontrada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DetalleInventario_Ubicacion");

                    b.Navigation("Activo");

                    b.Navigation("InventarioFisico");

                    b.Navigation("UbicacionEncontrada");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.EstadoActivo", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EstadoActivo_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.HistorialCambio", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistorialCambios_Empresa");

                    b.HasOne("InventarioEquipos.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistorialCambios_Usuario");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.InventarioFisico", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventarioFisico_Empresa");

                    b.HasOne("InventarioEquipos.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_InventarioFisico_Sede");

                    b.HasOne("InventarioEquipos.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_InventarioFisico_Ubicacion");

                    b.HasOne("InventarioEquipos.Domain.Entities.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventarioFisico_Usuario");

                    b.Navigation("Empresa");

                    b.Navigation("Sede");

                    b.Navigation("Ubicacion");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Mantenimiento", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Mantenimiento_Activo");

                    b.HasOne("InventarioEquipos.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Mantenimiento_Proveedor");

                    b.HasOne("InventarioEquipos.Domain.Entities.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany()
                        .HasForeignKey("IdTipoMantenimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Mantenimiento_Tipo");

                    b.Navigation("Activo");

                    b.Navigation("Proveedor");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.MotivoBaja", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MotivoBaja_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Proveedor", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedor_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Responsable", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Responsable_Area");

                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Responsable_Empresa");

                    b.HasOne("InventarioEquipos.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Responsable_Usuario");

                    b.Navigation("Area");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Sede", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sede_Empresa");

                    b.HasOne("InventarioEquipos.Domain.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sede_Pais");

                    b.Navigation("Empresa");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TipoMantenimiento_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Traslado", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Traslado_Activo");

                    b.HasOne("InventarioEquipos.Domain.Entities.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("IdUbicacionDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Traslado_Destino");

                    b.HasOne("InventarioEquipos.Domain.Entities.Ubicacion", "UbicacionOrigen")
                        .WithMany()
                        .HasForeignKey("IdUbicacionOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Traslado_Origen");

                    b.Navigation("Activo");

                    b.Navigation("UbicacionDestino");

                    b.Navigation("UbicacionOrigen");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.Ubicacion", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ubicacion_Sede");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("InventarioEquipos.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.HasOne("InventarioEquipos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioEmpresa_Empresa");

                    b.HasOne("InventarioEquipos.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioEmpresa_Usuario");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
